nextcloud/user_external

appinfo/info.xml

@jancborchardt @violoncelloCH 
Signed-off-by: Marius Blüm <marius@lineone.io>

Change links in info.xml

---

appinfo/info.xml

for #22 
cc @nextcloud/user_external 
Signed-off-by: Jonas Sulzer <jonas@violoncello.ch>

adapt info.xml to comply with minimum as of appstore documentation

---

.gitignore
Makefile

add Makefile to simplify releases

---

appinfo/info.xml

🚀 RELEASE: v0.5.1

---

README.md

fix broken readme links

---

.github/ISSUE_TEMPLATE/Bug_report.md

add 'User External App version' to issue template

---

appinfo/info.xml

🚀 RELEASE: v0.6.0

---

appinfo/info.xml

because the readme here on Github is always up to date

change documentation link to github readme

---

lib/basicauth.php

this should fix https://github.com/nextcloud/user_external/issues/45
all the best,
Lutz

basic authentication now follows redirects!

---

Makefile
appinfo/info.xml

🚀 RELEASE: v0.6.1

---

README.md

The previous explanation was somewhat inaccurate.
Fixes #
-
-
-

Increase clarity of the IMAP seaction in README.md

---

README.md

add basic auth configuration security warning

---

appinfo/info.xml

🚀 RELEASE: v0.6.2

---

Makefile
appinfo/info.xml
lib/base.php

fixes a bug introduced with #65 

hotfix & release v0.6.3

---

lib/base.php

resolves #14 
- add a `countUser()` method which counts the total number of user_external users

📦 NEW: support counting of total user_external users

---

lib/imap.php

🐛 FIX: variable groups not set in all cases

---

README.md
lib/xmpp.php

Add plaintext password authentication for prosody xmpp

---

appinfo/info.xml

resolves #103 
Changes (since v0.6.3):

🚀 RELEASE: v0.7.0

---

appinfo/info.xml

🚀 RELEASE: v0.8.0

---

lib/ssh.php

Minor comment update.
Signed-off-by: Sebastian Rachuj <rachus@web.de>

Fix comment for SSH module (it's not FTP)

---

lib/imap.php

🐛 FIX: starttls support for IMAP over curl

---

appinfo/info.xml

🚀 RELEASE: v0.9.1

---

appinfo/info.xml

and make the app compatible to Nextcloud Hub 19

🚀 RELEASE: v0.10.0

---

appinfo/info.xml

and make the app compatible to Nextcloud Hub 20

🚀 RELEASE: v0.11.0

---

.drone.yml
.travis.yml

🐛 FIX: update ci (versions of php and nextcloud used)

---

appinfo/info.xml

- make the app compatible to Nextcloud Hub 22
fixes #179 

🚀 RELEASE: v2.1.0 and make compatible to Nextcloud Hub 22

---

appinfo/info.xml

so we can release a beta first

🚀 RELEASE: v3.0.0beta1

---

CHANGELOG.md
appinfo/info.xml

prepare changelog and version number for a final release of v3 on Tuesday
please review @nextcloud/user_external so we can merge this on time :)

🚀 RELEASE: v3.0.0

---

lib/Base.php

Fix #203 
Signed-off-by: Glandos <bugs-github@antipoul.fr>

Trim doesn't accept null anymore

---

CHANGELOG.md
appinfo/info.xml

chore: min is 25, max is 27

---

CHANGELOG.md
appinfo/info.xml

prepare changelog for a new release
fixes #245 (once this is merged I can tag and create the release)

🚀 RELEASE: v3.3.0

---

README.md

Update README.md, add warning about fail2ban-like tools

---

CHANGELOG.md
appinfo/info.xml

resolves #246 
requires #249 to be merged
@nextcloud/user_external please review

🚀 RELEASE: v3.4.0
