nextcloud/user_external

appinfo/info.xml

for #22 
cc @jancborchardt @MariusBluem @rullzer 
Signed-off-by: Jonas Sulzer <jonas@violoncello.ch>

prepare to release in appstore

---

appinfo/info.xml
lib/base.php
lib/ftp.php
lib/imap.php
lib/smb.php
lib/webdavauth.php

as of #6 
cc @nextcloud/user_external 
1. occ check-code says for the appinfo.xml that the element `types` would not be expected. In NC12 documentation I can find `types`, in any newer version it's gone and I can't find any information with what I could replace / change this.
2. I would also need help with `OC_DB - private class must not be imported with a use statement` and `OC_DB - Static method of private class must not be called`. What has to be changed there?

occ check-code compliance

---

lib/imap.php

Prints IMAP errors and alerts to the nextcloud log. See #11
closes #11

Implements error handling for imap errors #11

---

README.md
appinfo/app.php
lib/basicauth.php
tests/basic_auth.php
tests/config.php

I've added code to authenticate against http basic access authentication.
In my setup I have a (self made) single sign on that can handle basic auth requests (because they are so insanely easy to implement) and use that as an identity and authentication provider.
This PR contains the code that runs on my setup.

Add authentication against basic auth

---

README.md

📖 DOC: sslmode is a string too && add possible values for sslmode

---

README.md
appinfo/app.php
appinfo/info.xml
lib/xmpp.php

This pull request contains an implementation for authentication against a Prosody XMPP MySQL database. The user can login to a nextcloud instance with his XMPP ID + password.

Add Prosody XMPP MySQL DB authentication

---

lib/imap.php

Signed-off-by: Sebastian <bash2@momou.ch>
When using user_external over imap with imapproxy (imapproxy.org) there are a lot of 'IMAP_Line_Read(): connection closed prematurely.' messages, because user_external doesn't close imap connection cleanly.
- Cleanly close imap connection

Cleanly close imap connection

---

README.md
appinfo/app.php
lib/ssh.php

thanks to @DavieDavieDave (nextcloud/apps#56): 
- allows to authenticate against an SSH2 server
- php-ssh2 PECL needed
TODO:

SSH password authentication

---

lib/base.php

Fix Querybuilder to find Users that have difference uid from displayName

---

README.md
lib/base.php
lib/imap.php

imap groups via domain-part
for #10 working with v15 from https://github.com/nextcloud/apps/compare/master...bjoern86:patch-1
- if there is no group equal to domain part of the new user create group
- add new user to the group
- make group and domain striping configurable via parameters
fixes #10 
fixes #76
fixes #68

optional imap groups via domain & make domain striping optional

---

lib/basicauth.php

Signed-off-by: Alejandro Liu <alejandro_liu@hotmail.com>
Fixes #58 
- Perform an initial check to prevent misconfigured Basic Auth URLs
This PR introduces an additional request in the BasicAuth external backend to check if the
provided URL is performing authentication.
The performance hit of the additional request is quite minor, as it only happens during session
login.  And doesn't happen again until the session logs out.

Address issue #58

---

lib/imap.php
lib/imap/imap_rcube.changes2upstream
lib/imap/imap_rcube.php

Add ssl_mode and force_caps to connection params, and correctly handle
AUTHENTICATE PLAIN in putLineC to reduce warnings in logs.
Signed-off-by: Scott Shambarger <devel@shambarger.net>
Fixes #56

Fix Issue #56: Undefined Indices in Logs

---

lib/imap.php

In the case of IMAP authentication, passing errors of the roundcube based module to the OC error logger.

added logging of errors for imap login

---

lib/smb.php

**Fixes:**
We had problems with logging in some users over SMB. The error:
The first, expected to be "incorrect", login try was successful. (Because of a bad formatting in the smbclient command.) I've added the needed space after the `-U` argument.
**Additional changes:**
I rewrote the multiple `if`/`elseif`/`else`'s & `goto`'s to a easier to maintain/more professional version. (one if + switch)
**Further Proposals:**
Re-evaluate if the `NT_STATUS_BAD_NETWORK_NAME` catch is really needed or at least add a check for successful login, instead of assuming the login was successful on that error.

Fixed SMB Login Issues

---

README.md

- finally i added a hint/warning for upgrading from <0.6.0 to manually rework the database according to https://github.com/nextcloud/user_external/issues/64#issuecomment-483224020 since it is the clearest statement i found about this topic (and it seems to work for a bunch of other guys and myself).
since there is no other doc or wiki i added it directly to the IMAP part of the main readme... anywhere else it would be pretty useless.
maybe it is enough to close #64...?
- additionally added a general warning to make sure to have unique `uid`s.

DOC: added a hint/warning for upgrading from <0.6.0 and a general warning for unique uids

---

appinfo/info.xml

🚀 RELEASE: v0.9.0

---

lib/basicauth.php

Fixes #141 
- Authorization header for OC_User_BasicAuth is now set with locally stream context instead globally with stream_context_set_default function.
- HTTP Redirects in OC_User_BasicAuth are disabled now, so authorization header can not be forwared to foreign servers.

Setting authorization header globally in basicauth.php is dangerous (fix for #141)

---

lib/imap.php

Fixes #145 
- just check imap server capabiities instead of pulling the complete folder list

fix long imap login delay on mailboxes with many folders

---

appinfo/info.xml
lib/Migration/Version0010Date20200630193751.php

Signed-off-by: Ole Morten <om@haaland.biz>
Fixes #165.
- Use new types.
- Bump compatibility: I'm not intimately familiar with Nextcloud's APIs, but I suppose using this new class is going to break compatibility with Nextcloud <21.

Use new types introduced in Nextcloud 21 and bump compatibility

---

README.md
appinfo/app.php
appinfo/info.xml
lib/AppInfo/Application.php
lib/Base.php
lib/BasicAuth.php
lib/FTP.php
lib/IMAP.php
lib/Migration/Version0010Date20200630193751.php
lib/SMB.php
lib/SSH.php
lib/WebDavAuth.php
lib/XMPP.php

Signed-off-by: Biermair Martin <martin.biermair@wimbergerhaus.at>
Fixes #186 
- increased supported nextcloud major version to 24
- migrating app.php to AppInfo/Application class
- increased to version 3.0.0, because breaking namespace changes
- adopting README and tests

migration/changes for nextcloud 23/24, bump UserExternal v3.0.0

---

Makefile

a small fix needed to make the automated release via workflow working

🐛 FIX: create correctly named archive file for workflow release

---

appinfo/info.xml

Fixes #240
- Add support for NC 28
This is untested, but only based on the success from #240

Add support for NC 28

---

lib/IMAP.php

Fixes #169 
The IMAP method allows user names with or without a domain part.  For user names without a domain part, it still tries to access the (then non-existing) domain, resulting in "Error: Undefined array key 1 at .../nextcloud/apps/user_external/lib/IMAP.php#85" log messages.

Fix out-of-bound array access (IMAP)

---

lib/IMAP.php

- evaluate cURL error code to log the reason why a login failed
Verifying login data can fail for a number of reasons like temporary connection failure to the IMAP server, Internal problems of the IMAP server, or actually wrong username / password combination.
This change logs the reason for login failures, helping server admins to diagnose login problems and better support their users.
Ideally, we would have an option to pass the reason upwards, so the NextCloud login system can show appropriate errors to users attempting to login.

Distinguish wrong credentials from other problems (IMAP)

---

lib/Base.php

🐛 FIX: wrong user count

---

appinfo/info.xml

Make the app compatible with Nextcloud 30
Fixes #260 
- Just a small fix of the appinfo.xml to make it run on NC30. I personally tested the IMAP authentication and did a quick check for changes in authentication API's or something in NC30 but could find none.

Make NC30 compatible
